### ISSUE TITLE
Version history shows "undefined"

### ISSUE THREAD

**Issue by niekomaatjes** [mrtazz/simplenote.vim#72]
1) Save a note through simplenote.vim;
2) Make some changes on https://app.simplenote.com/;
3) View Version History there, and move the slider one step left from "Current";
4) The text changes to "undefined".

This behavior is present in the iOS app too, but shows as "Today + seemingly random time" instead of "undefined".

**Comment by m1foley** [comment]
I'm unable to recreate.

When I create a new note with `:Simplenote -n`, I see this in my web browser and can't drag the slider:

![screenshot](https://monosnap.com/file/PebLnR8mPblLjHn2Mdfot2p0Y3uber.png)

When I then modify the file, the slider behaves as expected: it says the creation time and I can restore.

![screenshot](https://monosnap.com/file/9CPojrwZW5q1SxuGKXHRMlqSB7gtMt.png)

**Comment by atomicules** [comment]
Also not seeing this. You're not by chance running a really old version of Simplenote.vim are you? Because I seem to recall this used to be an issue, but commits were made to fix it awhile ago.

See:  https://github.com/mrtazz/simplenote.vim/commit/f0fa5c80c35d470779a76ffa728d1fc9f510c5dc and issue #45.

**Comment by niekomaatjes** [comment]
You're right, I mistakenly thought I had a recent version. Thanks for taking a look!
